---
title : Imputation
author:
  name : 오태환
date: "`r Sys.Date()`"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1) Importing data

```{r}
library(tidyverse)
library(mice)
library(impute)
data = read_csv("C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_calculated_data.csv")
```

# 2) Change ? to NA
```{r}
data[data == "?"] = NA

for(i in 1:ncol(data)){
  data[,i] = data[,i] %>% unlist() %>% as.numeric
}

summary(data)

data$Attr67[data$Attr67 == -Inf] = NA
```

# 3) NA가 많은 Attr37 제거 후 imputation 진행

## 3-1) MICE 패키지의 PMM방식 사용

```{r}

tempdata = data %>% select(-c("X1","Attr1","Attr7","Attr42","Attr36","Attr46","Attr8","Attr12","Attr15","Attr28","Attr45","Attr23","Attr50","Attr62","Attr48","Attr35","Attr45","Attr27","Attr40","Attr44","Attr54","Attr56", "Attr58",  "Attr70", "class"))


imp = mice(tempdata, seed = 1234, m = 20, ridge = 0.001)

complete.data = complete(imp)

for(i in 1:ncol(complete.data)){
  if(sum(is.na(complete.data[,i] == T))){
    colname = colnames(complete.data)[i]
    cat("Attr", colname , "has", sum(is.na(complete.data[,i])), "NAs", "\n")
  }
}



```

```{r}
imp$method
```

### PMM(Predictive mean matching) 방식으로 Imputation을 진행했다.

## 저장하자
```{r}

complete.data$class = data$class
complete.data$Attr70 = data$Attr70

write.csv(complete.data, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_mice.csv", row.names = FALSE)
```

## 3-2) impute 함수의 KNN imputation 활용

```{r}
knn_data = data %>% select(-c("X1","Attr70", "class"))

knn_imputed = impute.knn(as.matrix(knn_data))
```

### 저장하자
```{r}
complete_data_knn = data.frame(knn_imputed$data)


complete_data_knn$Attr70 = data$Attr70
complete_data_knn$class = data$class


View(complete_data_knn)

write.csv(complete_data_knn, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_knn.csv", row.names = FALSE)
```


## 3-3) Mean Imputation

### 가장 간단하게 그 칼럼의 mean 값으로 NA를 채워넣는 방법이다.

```{r}


complete_data_mean = as.matrix(data)

for (i in 1:ncol(complete_data_mean)){
  complete_data_mean[,i][is.na(complete_data_mean[,i])] <- mean(complete_data_mean[,i][order(complete_data_mean[,i])[4:(nrow(complete_data_mean)-3)]], na.rm=TRUE)
}

complete_data_mean = data.frame(complete_data_mean)

write.csv(complete_data_mean, "new_imputed_data_mean.csv", row.names = FALSE)
```

## 3-4) Median Imputation

### 그 칼럼의 median 값으로 NA를 채워넣는 방법이다.

```{r}


complete_data_med = as.matrix(data)

for (i in 1:ncol(complete_data_med)){
  complete_data_med[,i][is.na(complete_data_med[,i])] <- median(complete_data_med[,i][order(complete_data_med[,i])], na.rm = TRUE)
}

complete_data_med = data.frame(complete_data_med)

write.csv(complete_data_med, "new_imputed_data_med.csv", row.names = FALSE)
```
