---
title : Transformation
author:
  name : 오태환
date: "`r Sys.Date()`"
output:
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 0) Importing Data
```{r}
library(tidyverse)
library(fBasics)
mice_data = read_csv("C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_mice.csv")
knn_data = read_csv("C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_knn.csv")
mean_data = read_csv("C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_mean.csv")
med_data= read_csv("C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_imputed_data_med.csv")

mice_data %>% View()
```

# 1) Transformation

## 1-a) Mice Imputated Data

```{r}
for(i in 1:(ncol(mice_data)-1)){
  skew_score = skewness(mice_data[,i])
  if(skew_score > 1){
    if(min(mice_data[,i]) <= 0){
    mice_data[,i] = log(mice_data[,i] - min(mice_data[,i]) + 1)
    }
    else{
      mice_data[,i] = log(mice_data[,i])
    }
  }
  if(skew_score < -1){
    mice_data[,i] = exp(mice_data[,i])
  }
}

write.csv(mice_data, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_transfromed_data_mice.csv", row.names = FALSE)

```

### 왜도가 1 기준으로 큰 것들은 log transformation, -1보다 작은 것들은 exponential transformation 으로 왜도를 줄여주었다.

## 1-b) KNN Imputed Data
```{r}
for(i in 1:(ncol(knn_data)-1)){
  skew_score = skewness(knn_data[,i])
  if(skew_score > 1){
    if(min(knn_data[,i]) <= 0){
    knn_data[,i] = log(knn_data[,i] - min(knn_data[,i]) + 1)
    }
    else{
      knn_data[,i] = log(knn_data[,i])
    }
  }
  if(skew_score < -1){
    knn_data[,i] = exp(knn_data[,i])
  }
}


write.csv(knn_data, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_transfromed_data_knn.csv", row.names = FALSE)
```

## 1-c) MEAN Imputed Data
```{r}
for(i in 1:(ncol(mean_data)-1)){
  skew_score = skewness(mean_data[,i])
  if(skew_score > 1){
    if(min(mean_data[,i]) <= 0){
    mean_data[,i] = log(mean_data[,i] - min(mean_data[,i]) + 1)
    }
    else{
      mean_data[,i] = log(mean_data[,i])
    }
  }
  if(skew_score < -1){
    mean_data[,i] = exp(mean_data[,i])
  }
}


write.csv(mean_data, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_transfromed_data_mean.csv", row.names = FALSE)
```

## 1-c) MEDIAN Imputed Data
```{r}
for(i in 1:(ncol(med_data)-1)){
  skew_score = skewness(med_data[,i])
  if(skew_score > 1){
    if(min(med_data[,i]) <= 0){
    med_data[,i] = log(med_data[,i] - min(med_data[,i]) + 1)
    }
    else{
      med_data[,i] = log(med_data[,i])
    }
  }
  if(skew_score < -1){
    med_data[,i] = exp(med_data[,i])
  }
}


write.csv(med_data, "C:/Users/dhxog/Desktop/ESC4-1/Final_Project/ESC20SPRING_team4/finalEDA/data/new_transfromed_data_med.csv", row.names = FALSE)
```